version: "3.8"

services:
  web:
    build: ./frontend
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/app
  api:
    build: ./backend
    ports:
      - 3001:3001
    environment:
      DB_URL: mongodb://db/vidly
    volumes:
      - ./backend:/app
  api_test:
    image: vidly-api
    environment:
      DB_URL: mongodb://db/vidly
    volumes:
      - ./backend:/app
    command: npm run test
  db:
    image: mongo:4.0-xenial
    ports:
      - 27017:27017
    volumes:
      - vidly:/data/db
networks:
  vidly_network:
volumes:
  vidly:
